# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pickup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import resources_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1208, 800)
        Form.setMinimumSize(QtCore.QSize(1208, 800))
        Form.setMaximumSize(QtCore.QSize(1208, 800))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 60, 1191, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wifiLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.wifiLabel_2.setMinimumSize(QtCore.QSize(15, 12))
        self.wifiLabel_2.setMaximumSize(QtCore.QSize(15, 12))
        self.wifiLabel_2.setText("")
        self.wifiLabel_2.setPixmap(QtGui.QPixmap(":/icons/icons/Signal_Full.png"))
        self.wifiLabel_2.setScaledContents(True)
        self.wifiLabel_2.setObjectName("wifiLabel_2")
        self.gridLayout_2.addWidget(self.wifiLabel_2, 0, 7, 1, 1)
        self.signalLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.signalLabel_2.setMinimumSize(QtCore.QSize(15, 12))
        self.signalLabel_2.setMaximumSize(QtCore.QSize(15, 12))
        self.signalLabel_2.setText("")
        self.signalLabel_2.setPixmap(QtGui.QPixmap(":/icons/icons/wifi_full.png"))
        self.signalLabel_2.setScaledContents(True)
        self.signalLabel_2.setObjectName("signalLabel_2")
        self.gridLayout_2.addWidget(self.signalLabel_2, 0, 5, 1, 1)
        self.logoLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.logoLabel_2.setMinimumSize(QtCore.QSize(230, 30))
        self.logoLabel_2.setMaximumSize(QtCore.QSize(230, 30))
        self.logoLabel_2.setText("")
        self.logoLabel_2.setPixmap(QtGui.QPixmap(":/icons/icons/Logo.png"))
        self.logoLabel_2.setScaledContents(True)
        self.logoLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel_2.setObjectName("logoLabel_2")
        self.gridLayout_2.addWidget(self.logoLabel_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(24, 12))
        self.label_5.setMaximumSize(QtCore.QSize(24, 12))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/icons/battery_full.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 9, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(60, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 10, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 0, 1, 1)
       
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(70, 150, 641, 521))
        self.frame.setMinimumSize(QtCore.QSize(514, 383))
        self.frame.setMaximumSize(QtCore.QSize(99999, 99999))
        self.frame.setStyleSheet("QFrame {\n"
"  background: #ffffff;\n"
"  border-radius: 20px;\n"
"  height: 864.62px;\n"
"  position: relative;\n"
"  box-shadow: 0px 2px 60px 0px rgba(20, 65, 120, 0.02);\n"
"\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(210, 130, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(200, 170, 251, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
" color: rgba(37, 37, 37, 150);}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(260, 30, 121, 101))
        self.label_6.setMinimumSize(QtCore.QSize(80, 67))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/icons/only package.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 220, 100, 80))
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 80))
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 80))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background: #f9fafb;\n"
"    border: 1px solid #dadfe6;\n"
"    border-radius: 14px;\n"
"    font-size: 40px;\n"
"    color: #2a313a;\n"
"    min-width: 80px;\n"
"    min-height: 65px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 220, 100, 80))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 80))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 80))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background: #f9fafb;\n"
"    border: 1px solid #dadfe6;\n"
"    border-radius: 14px;\n"
"    font-size: 40px;\n"
"    color: #2a313a;\n"
"    min-width: 80px;\n"
"    min-height: 65px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(340, 220, 100, 80))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(100, 80))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 80))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background: #f9fafb;\n"
"    border: 1px solid #dadfe6;\n"
"    border-radius: 14px;\n"
"    font-size: 40px;\n"
"    color: #2a313a;\n"
"    min-width: 80px;\n"
"    min-height: 65px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(470, 220, 100, 80))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(100, 80))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 80))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background: #f9fafb;\n"
"    border: 1px solid #dadfe6;\n"
"    border-radius: 14px;\n"
"    font-size: 40px;\n"
"    color: #2a313a;\n"
"    min-width: 80px;\n"
"    min-height: 65px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(240, 310, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
" color: rgba(37, 37, 37, 150);}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(30, 390, 581, 91))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background: #f9fafb;\n"
"    border-radius:8px;\n"
"    border: none;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(200, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(90, 40, 411, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
" color: rgba(37, 37, 37, 150);}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        # 计算对称布局的位置
        # 屏幕宽度：1280px
        # frame宽度：641px，frame_2宽度：371px
        # 两frame间距：约50px
        # 总内容宽度：641 + 50 + 371 = 1062px
        # 左右边距：(1280 - 1062) / 2 = 109px
        
        # 调整左侧frame位置
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(180, 150, 641, 521))  # 左边距109px
        
        # 调整右侧frame_2位置
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(820, 150, 371, 521))  # 109 + 641 + 50 = 800
        self.frame_2.setMinimumSize(QtCore.QSize(320, 383))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("QFrame {\n"
"  background: #ffffff;\n"
"  border-radius: 20px;\n"
"  height: 864.62px;\n"
"  position: relative;\n"
"  box-shadow: 0px 2px 60px 0px rgba(20, 65, 120, 0.02);\n"
"\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(120, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 70, 311, 381))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_6.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_13.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_13.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background: #4caf50;             /* 鲜亮红色背景 */\n"
"    color: #fff;                     /* 白色字体 */\n"
"    border: none;                    /* 无边框 */\n"
"    border-radius: 16px;             /* 大圆角，根据按钮高度调整 */\n"
"    font-size: 14px;                 /* 字体大小 */\n"
"    font-family: \'Microsoft YaHei\';  /* 字体族 */\n"
"    font-weight: bold;               /* 字体加粗 */\n"
"    min-width: 74px;                 /* 最小宽度 */\n"
"    min-height: 54px;                /* 最小高度 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #388e3c;             /* 按下时稍深的绿色 */\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_5.addWidget(self.pushButton_13, 3, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_2.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_9.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_9.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_5.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_8.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_5.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_12.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_12.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background: #ff6f6f;             /* 鲜亮红色背景 */\n"
"    color: #fff;                     /* 白色字体 */\n"
"    border: none;                    /* 无边框 */\n"
"    border-radius: 16px;             /* 大圆角，根据按钮高度调整 */\n"
"    font-size: 14px;                 /* 字体大小 */\n"
"    font-family: \'Microsoft YaHei\';  /* 字体族 */\n"
"    font-weight: bold;               /* 字体加粗 */\n"
"    min-width: 74px;                 /* 最小宽度 */\n"
"    min-height: 54px;                /* 最小高度 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #ff4c4c;             /* 按下时稍深的红色 */\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_5.addWidget(self.pushButton_12, 3, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_11.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_11.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_4.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_10.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_10.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 2, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_7.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_7.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setMinimumSize(QtCore.QSize(74, 54))
        self.pushButton_3.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "17:04"))
        self.label_2.setText(_translate("Form", "请输入取件码"))
        self.label_3.setText(_translate("Form", "输入4位数字取件码完成派件"))
        self.label_7.setText(_translate("Form", "请使用右侧键盘输入"))
        self.label_8.setText(_translate("Form", "温馨提示"))
        self.label_9.setText(_translate("Form", "• 请确保取件码正确无误，输入完成后点击确认派件"))
        self.label_4.setText(_translate("Form", "数字键盘"))
        self.pushButton_6.setText(_translate("Form", "4"))
        self.pushButton_13.setText(_translate("Form", "确认"))
        self.pushButton_2.setText(_translate("Form", "1"))
        self.pushButton_9.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_12.setText(_translate("Form", "清除"))
        self.pushButton_11.setText(_translate("Form", "0"))
        self.pushButton_4.setText(_translate("Form", "3"))
        self.pushButton_10.setText(_translate("Form", "9"))
        self.pushButton_7.setText(_translate("Form", "6"))
        self.pushButton_3.setText(_translate("Form", "2"))
import resources_rc
