# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '02_send.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1208, 800)
        Form.setMinimumSize(QtCore.QSize(1208, 800))
        Form.setMaximumSize(QtCore.QSize(1208, 800))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 60, 1191, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 8, 1, 1)
        self.lblwifi = QtWidgets.QLabel(self.layoutWidget)
        self.lblwifi.setMinimumSize(QtCore.QSize(15, 12))
        self.lblwifi.setMaximumSize(QtCore.QSize(15, 12))
        self.lblwifi.setText("")
        self.lblwifi.setPixmap(QtGui.QPixmap(":/icons/icons/wifi_full.png"))
        self.lblwifi.setScaledContents(True)
        self.lblwifi.setObjectName("lblwifi")
        self.gridLayout_2.addWidget(self.lblwifi, 0, 5, 1, 1)
        self.lblTime = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblTime.setFont(font)
        self.lblTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTime.setObjectName("lblTime")
        self.gridLayout_2.addWidget(self.lblTime, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.lblLogo = QtWidgets.QLabel(self.layoutWidget)
        self.lblLogo.setMinimumSize(QtCore.QSize(230, 30))
        self.lblLogo.setMaximumSize(QtCore.QSize(230, 30))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/icons/icons/Logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.gridLayout_2.addWidget(self.lblLogo, 0, 1, 1, 1)
        self.lblBattery = QtWidgets.QLabel(self.layoutWidget)
        self.lblBattery.setMinimumSize(QtCore.QSize(24, 12))
        self.lblBattery.setMaximumSize(QtCore.QSize(24, 12))
        self.lblBattery.setText("")
        self.lblBattery.setPixmap(QtGui.QPixmap(":/icons/icons/battery_full.png"))
        self.lblBattery.setScaledContents(True)
        self.lblBattery.setObjectName("lblBattery")
        self.gridLayout_2.addWidget(self.lblBattery, 0, 9, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(60, 13, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 10, 1, 1)
        self.lblSignal = QtWidgets.QLabel(self.layoutWidget)
        self.lblSignal.setMinimumSize(QtCore.QSize(15, 12))
        self.lblSignal.setMaximumSize(QtCore.QSize(15, 12))
        self.lblSignal.setText("")
        self.lblSignal.setPixmap(QtGui.QPixmap(":/icons/icons/Signal_Full.png"))
        self.lblSignal.setScaledContents(True)
        self.lblSignal.setObjectName("lblSignal")
        self.gridLayout_2.addWidget(self.lblSignal, 0, 7, 1, 1)
        self.frmInputArea = QtWidgets.QFrame(Form)
        self.frmInputArea.setGeometry(QtCore.QRect(70, 150, 641, 521))
        self.frmInputArea.setMinimumSize(QtCore.QSize(514, 383))
        self.frmInputArea.setMaximumSize(QtCore.QSize(999999, 999999))
        self.frmInputArea.setStyleSheet("QFrame {\n"
"  background: #ffffff;\n"
"  border-radius: 20px;\n"
"  height: 864.62px;\n"
"  position: relative;\n"
"}\n"
"")
        self.frmInputArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmInputArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmInputArea.setObjectName("frmInputArea")
        self.label_2 = QtWidgets.QLabel(self.frmInputArea)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frmInputArea)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frmInputArea)
        self.label_7.setGeometry(QtCore.QRect(290, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.frmInputArea)
        self.label_9.setGeometry(QtCore.QRect(40, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.frame_5 = QtWidgets.QFrame(self.frmInputArea)
        self.frame_5.setGeometry(QtCore.QRect(40, 230, 561, 91))
        self.frame_5.setStyleSheet("QFrame{  \n"
"background: #f5f7fa;\n"
"  border-radius: 8px;\n"
"  height: 102.57px;\n"
"  position: relative\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 10, 299, 81))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.editRoom = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.editRoom.setMinimumSize(QtCore.QSize(130, 50))
        self.editRoom.setMaximumSize(QtCore.QSize(130, 50))
        self.editRoom.setStyleSheet("QLineEdit{\n"
"border: 2px solid #e0e5ea;         /* 浅灰色描边 */\n"
"    border-radius: 8px;               /* 圆角半径（根据高度调整）*/\n"
"    background: #fff;                  /* 白底 */\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 12px;                   /* 字体大小 */\n"
"    color: #222;                       /* 文字颜色 */\n"
"    padding-left: 18px;                /* 左侧内边距让文字不贴边 */\n"
"    height: 56px;                      /* 高度，和实际按钮一致 */\n"
"}")
        self.editRoom.setObjectName("editRoom")
        self.gridLayout_4.addWidget(self.editRoom, 0, 2, 1, 1)
        self.lblRoomSuffix = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lblRoomSuffix.setFont(font)
        self.lblRoomSuffix.setStyleSheet("QLabel{\n"
"rgba(25, 25, 25, 50)\n"
"\n"
"}")
        self.lblRoomSuffix.setObjectName("lblRoomSuffix")
        self.gridLayout_4.addWidget(self.lblRoomSuffix, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 3, 1, 1)
        self.lblRoomTip = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.lblRoomTip.setFont(font)
        self.lblRoomTip.setStyleSheet("QLabel{\n"
"rgba(25, 25, 25, 50)\n"
"\n"
"}")
        self.lblRoomTip.setObjectName("lblRoomTip")
        self.gridLayout_4.addWidget(self.lblRoomTip, 0, 0, 1, 1)
        self.frmCurrentAddress = QtWidgets.QLabel(self.frmInputArea)
        self.frmCurrentAddress.setGeometry(QtCore.QRect(40, 390, 561, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.frmCurrentAddress.setFont(font)
        self.frmCurrentAddress.setStyleSheet("QLabel {\n"
"    background: #eaf5ff;                           /* 浅蓝背景 */\n"
"    border: 2px dashed #3777c2;                    /* 蓝色虚线边框 */\n"
"    border-radius: 12px;                            /* 圆角 */\n"
"    color: #222;                                    /* 字体颜色 */\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;                              /* 加粗 */\n"
"    padding: 14px 10px 14px 16px;                   /* 内边距（可调）*/\n"
"}\n"
"")
        self.frmCurrentAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.frmCurrentAddress.setObjectName("frmCurrentAddress")
        self.lblCurrentAddressTip = QtWidgets.QLabel(self.frmInputArea)
        self.lblCurrentAddressTip.setGeometry(QtCore.QRect(40, 360, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lblCurrentAddressTip.setFont(font)
        self.lblCurrentAddressTip.setStyleSheet("QLabel {\n"
"    color: #99b7db;          /* 浅蓝灰色（比主文字浅）*/\n"
"    font-weight: normal;     /* 不加粗 */\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent; /* 通常不用背景 */\n"
"    padding-left: 2px;       /* 和内容略微错开一点 */\n"
"}\n"
"")
        self.lblCurrentAddressTip.setObjectName("lblCurrentAddressTip")
        self.cmbBuilding = QtWidgets.QComboBox(self.frmInputArea)
        self.cmbBuilding.setGeometry(QtCore.QRect(90, 110, 130, 50))
        self.cmbBuilding.setMinimumSize(QtCore.QSize(130, 50))
        self.cmbBuilding.setMaximumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        # font.setPointSize(-1)
        self.cmbBuilding.setFont(font)
        self.cmbBuilding.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cmbBuilding.setStyleSheet(" QComboBox{\n"
"     border: 2px solid #e0e5ea; \n"
"    border-radius: 8px;\n"
"    background: #fff; \n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 16px; \n"
"    color: #222;\n"
"    padding-left: 18px; \n"
"    height: 56px; \n"
"}\n"
"")
        self.cmbBuilding.setObjectName("cmbBuilding")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbBuilding.addItem("")
        self.cmbUnit = QtWidgets.QComboBox(self.frmInputArea)
        self.cmbUnit.setGeometry(QtCore.QRect(360, 110, 130, 50))
        self.cmbUnit.setMinimumSize(QtCore.QSize(130, 50))
        self.cmbUnit.setMaximumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.cmbUnit.setFont(font)
        self.cmbUnit.setStyleSheet(" QComboBox{\\n     border: 2px solid #e0e5ea; \\n    border-radius: 8px;\\n    background: #fff; \\n    font-family: \'Microsoft YaHei\';\\n    font-size: 16px; \\n    color: #222;\\n    padding-left: 18px; \\n    height: 56px; \\n}\\n")
        self.cmbUnit.setObjectName("cmbUnit")
        self.cmbUnit.addItem("")
        self.cmbUnit.addItem("")
        self.cmbUnit.addItem("")
        self.cmbUnit.addItem("")
        self.cmbUnit.addItem("")
        self.cmbUnit.addItem("")
        self.frmKeypad = QtWidgets.QFrame(Form)
        self.frmKeypad.setGeometry(QtCore.QRect(820, 150, 371, 521))
        self.frmKeypad.setMinimumSize(QtCore.QSize(320, 383))
        self.frmKeypad.setMaximumSize(QtCore.QSize(99999, 99999))
        self.frmKeypad.setStyleSheet("QFrame {\n"
"  background: #ffffff;\n"
"  border-radius: 20px;\n"
"  height: 864.62px;\n"
"  position: relative;\n"
"\n"
"}\n"
"")
        self.frmKeypad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmKeypad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmKeypad.setObjectName("frmKeypad")
        self.label_12 = QtWidgets.QLabel(self.frmKeypad)
        self.label_12.setGeometry(QtCore.QRect(40, 400, 111, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.layoutWidget1 = QtWidgets.QWidget(self.frmKeypad)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 40, 311, 351))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnNum5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum5.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum5.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum5.setFont(font)
        self.btnNum5.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum5.setObjectName("btnNum5")
        self.gridLayout_5.addWidget(self.btnNum5, 1, 1, 1, 1)
        self.btnNum2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum2.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum2.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum2.setFont(font)
        self.btnNum2.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum2.setObjectName("btnNum2")
        self.gridLayout_5.addWidget(self.btnNum2, 0, 1, 1, 1)
        self.btnNum8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum8.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum8.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum8.setFont(font)
        self.btnNum8.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum8.setObjectName("btnNum8")
        self.gridLayout_5.addWidget(self.btnNum8, 2, 1, 1, 1)
        self.btnNum4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum4.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum4.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum4.setFont(font)
        self.btnNum4.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum4.setObjectName("btnNum4")
        self.gridLayout_5.addWidget(self.btnNum4, 1, 0, 1, 1)
        self.btnNum1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum1.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum1.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum1.setFont(font)
        self.btnNum1.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum1.setObjectName("btnNum1")
        self.gridLayout_5.addWidget(self.btnNum1, 0, 0, 1, 1)
        self.btnNumClear = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNumClear.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNumClear.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        # font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnNumClear.setFont(font)
        self.btnNumClear.setStyleSheet("QPushButton {\n"
"    background: #ff6f6f;             /* 鲜亮红色背景 */\n"
"    color: #fff;                     /* 白色字体 */\n"
"    border: none;                    /* 无边框 */\n"
"    border-radius: 16px;             /* 大圆角，根据按钮高度调整 */\n"
"    font-size: 14px;                 /* 字体大小 */\n"
"    font-family: \'Microsoft YaHei\';  /* 字体族 */\n"
"    font-weight: bold;               /* 字体加粗 */\n"
"    min-width: 74px;                 /* 最小宽度 */\n"
"    min-height: 54px;                /* 最小高度 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #ff4c4c;             /* 按下时稍深的红色 */\n"
"}\n"
"")
        self.btnNumClear.setObjectName("btnNumClear")
        self.gridLayout_5.addWidget(self.btnNumClear, 3, 0, 1, 1)
        self.btnNumConfirm = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNumConfirm.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNumConfirm.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        # font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnNumConfirm.setFont(font)
        self.btnNumConfirm.setStyleSheet("QPushButton {\n"
"    background: #4caf50;             /* 鲜亮红色背景 */\n"
"    color: #fff;                     /* 白色字体 */\n"
"    border: none;                    /* 无边框 */\n"
"    border-radius: 16px;             /* 大圆角，根据按钮高度调整 */\n"
"    font-size: 14px;                 /* 字体大小 */\n"
"    font-family: \'Microsoft YaHei\';  /* 字体族 */\n"
"    font-weight: bold;               /* 字体加粗 */\n"
"    min-width: 74px;                 /* 最小宽度 */\n"
"    min-height: 54px;                /* 最小高度 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #388e3c;             /* 按下时稍深的绿色 */\n"
"}\n"
"")
        self.btnNumConfirm.setObjectName("btnNumConfirm")
        self.gridLayout_5.addWidget(self.btnNumConfirm, 3, 2, 1, 1)
        self.btnNum6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum6.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum6.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum6.setFont(font)
        self.btnNum6.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum6.setObjectName("btnNum6")
        self.gridLayout_5.addWidget(self.btnNum6, 1, 2, 1, 1)
        self.btnNum7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum7.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum7.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum7.setFont(font)
        self.btnNum7.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum7.setObjectName("btnNum7")
        self.gridLayout_5.addWidget(self.btnNum7, 2, 0, 1, 1)
        self.btnNum3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum3.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum3.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum3.setFont(font)
        self.btnNum3.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum3.setObjectName("btnNum3")
        self.gridLayout_5.addWidget(self.btnNum3, 0, 2, 1, 1)
        self.btnNum9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum9.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum9.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum9.setFont(font)
        self.btnNum9.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum9.setObjectName("btnNum9")
        self.gridLayout_5.addWidget(self.btnNum9, 2, 2, 1, 1)
        self.btnNum0 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnNum0.setMinimumSize(QtCore.QSize(74, 54))
        self.btnNum0.setMaximumSize(QtCore.QSize(64, 42))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        # font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnNum0.setFont(font)
        self.btnNum0.setStyleSheet("QPushButton {\n"
"    background: #fafbfc;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 12px;\n"
"    font-size: 20px;\n"
"    color: #222;\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f2f6ff;\n"
"}")
        self.btnNum0.setObjectName("btnNum0")
        self.gridLayout_5.addWidget(self.btnNum0, 3, 1, 1, 1)
        self.lblKeypadTitle = QtWidgets.QLabel(self.frmKeypad)
        self.lblKeypadTitle.setGeometry(QtCore.QRect(40, 10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblKeypadTitle.setFont(font)
        self.lblKeypadTitle.setObjectName("lblKeypadTitle")
        self.widget = QtWidgets.QWidget(self.frmKeypad)
        self.widget.setGeometry(QtCore.QRect(30, 430, 311, 42))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnQuickAddr1 = QtWidgets.QPushButton(self.widget)
        self.btnQuickAddr1.setMinimumSize(QtCore.QSize(90, 40))
        self.btnQuickAddr1.setMaximumSize(QtCore.QSize(90, 40))
        self.btnQuickAddr1.setStyleSheet("QPushButton {\n"
"    background: #fff;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 8px;\n"
"    color: #222;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;\n"
"    font-size: 11px;"
"}\n"
"QPushButton:pressed {\n"
"    background: #f6f9fb;     /* 按下时轻微变灰 */\n"
"    border-color: #b6b9be;   /* 边框变深一点 */\n"
"}")
        self.btnQuickAddr1.setObjectName("btnQuickAddr1")
        self.horizontalLayout.addWidget(self.btnQuickAddr1)
        self.btnQuickAddr2 = QtWidgets.QPushButton(self.widget)
        self.btnQuickAddr2.setMinimumSize(QtCore.QSize(90, 40))
        self.btnQuickAddr2.setMaximumSize(QtCore.QSize(90, 40))
        self.btnQuickAddr2.setStyleSheet("QPushButton {\n"
"    background: #fff;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 8px;\n"
"    color: #222;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;\n"
"    font-size: 11px;"
"}\n"
"QPushButton:pressed {\n"
"    background: #f6f9fb;     /* 按下时轻微变灰 */\n"
"    border-color: #b6b9be;   /* 边框变深一点 */\n"
"}")
        self.btnQuickAddr2.setObjectName("btnQuickAddr2")
        self.horizontalLayout.addWidget(self.btnQuickAddr2)
        self.btnQuickAddr3 = QtWidgets.QPushButton(self.widget)
        self.btnQuickAddr3.setMinimumSize(QtCore.QSize(90, 40))
        self.btnQuickAddr3.setMaximumSize(QtCore.QSize(90, 40))
        self.btnQuickAddr3.setStyleSheet("QPushButton {\n"
"    background: #fff;\n"
"    border: 2px solid #e0e5ea;\n"
"    border-radius: 8px;\n"
"    color: #222;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;\n"
"    font-size: 11px;"
"}\n"
"QPushButton:pressed {\n"
"    background: #f6f9fb;     /* 按下时轻微变灰 */\n"
"    border-color: #b6b9be;   /* 边框变深一点 */\n"
"}")
        self.btnQuickAddr3.setObjectName("btnQuickAddr3")
        self.horizontalLayout.addWidget(self.btnQuickAddr3)
        self.btnQuickAddr1.raise_()
        self.btnQuickAddr3.raise_()
        self.label_12.raise_()
        self.layoutWidget.raise_()
        self.lblKeypadTitle.raise_()
        self.btnQuickAddr2.raise_()
        self.btnCreateTaskConfirm = QtWidgets.QPushButton(Form)
        self.btnCreateTaskConfirm.setGeometry(QtCore.QRect(70, 700, 641, 54))
        self.btnCreateTaskConfirm.setMinimumSize(QtCore.QSize(200, 54))
        self.btnCreateTaskConfirm.setMaximumSize(QtCore.QSize(800, 54))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        # font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnCreateTaskConfirm.setFont(font)
        self.btnCreateTaskConfirm.setMouseTracking(False)
        self.btnCreateTaskConfirm.setTabletTracking(False)
        self.btnCreateTaskConfirm.setAcceptDrops(False)
        self.btnCreateTaskConfirm.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    color: #FFF;\n"
"    border-radius: 16px;\n"
"    font-size: 18px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 514px;\n"
"    min-height: 54px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.btnCreateTaskConfirm.setAutoDefault(False)
        self.btnCreateTaskConfirm.setDefault(False)
        self.btnCreateTaskConfirm.setObjectName("btnCreateTaskConfirm")
        self.btnBack = QtWidgets.QPushButton(Form)
        self.btnBack.setGeometry(QtCore.QRect(1100, 700, 111, 40))
        self.btnBack.setMinimumSize(QtCore.QSize(111, 0))
        self.btnBack.setMaximumSize(QtCore.QSize(111, 16777215))
        self.btnBack.setStyleSheet("QPushButton {\n"
"    background: transparent;    /* 没有背景 */\n"
"    border: none;               /* 没有边框 */\n"
"    color: rgba(37, 37, 37, 80);  /* 浅灰色，和界面一致 */\n"
"    font-size: 20px;            /* 字体大小，可按实际需求调 */\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;        /* 不加粗 */\n"
"    padding: 0 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #888e99;             /* 按下时颜色略深 */\n"
"}\n"
"")
        self.btnBack.setObjectName("btnBack")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        combo_style = """
        QComboBox {
          border: 2px solid #e0e5ea;
          border-radius: 8px;
           background-color: white;
            font-family: 'Microsoft YaHei';
            font-size: 16px;
            color: #222;
            padding-left: 16px;
            min-height: 36px;
        }

        QComboBox::drop-down {
            subcontrol-origin: padding;
           subcontrol-position: top right;
           width: 25px;
            border-left-width: 0px;  /* 移除左边框线 */
            border-top-right-radius: 0px;
            border-bottom-right-radius: 8px;
        }

        QComboBox::down-arrow {
            image: url(:/icons/icons/down-arrow.png);  /* 使用您项目中的下拉箭头图标 */
            width: 12px;
            height: 5px;
        }

        QComboBox QAbstractItemView {
            border: 1px solid #e0e5ea;
            border-radius: 0px;  /* 这里是关键：移除下拉列表的圆角 */
            background-color: white;
            selection-background-color: #e0e5ea;
        }
        """

        self.cmbBuilding.setStyleSheet(combo_style)
        self.cmbUnit.setStyleSheet(combo_style)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblTime.setText(_translate("Form", "17:04"))
        self.label_2.setText(_translate("Form", "添加配送地址"))
        self.label_3.setText(_translate("Form", "栋号："))
        self.label_7.setText(_translate("Form", "单元号："))
        self.label_9.setText(_translate("Form", "房间号："))
        self.lblRoomSuffix.setText(_translate("Form", "室"))
        self.lblRoomTip.setText(_translate("Form", "请输入房间号："))
        self.frmCurrentAddress.setText(_translate("Form", "1栋 2单元 301室"))
        self.lblCurrentAddressTip.setText(_translate("Form", "当前地址："))
        self.cmbBuilding.setItemText(0, _translate("Form", "1栋"))
        self.cmbBuilding.setItemText(1, _translate("Form", "2栋"))
        self.cmbBuilding.setItemText(2, _translate("Form", "3栋"))
        self.cmbBuilding.setItemText(3, _translate("Form", "4栋"))
        self.cmbBuilding.setItemText(4, _translate("Form", "5栋"))
        self.cmbBuilding.setItemText(5, _translate("Form", "6栋"))
        self.cmbBuilding.setItemText(6, _translate("Form", "7栋"))
        self.cmbBuilding.setItemText(7, _translate("Form", "8栋"))
        self.cmbBuilding.setItemText(8, _translate("Form", "9栋"))
        self.cmbBuilding.setItemText(9, _translate("Form", "10栋"))
        self.cmbUnit.setItemText(0, _translate("Form", "1单元"))
        self.cmbUnit.setItemText(1, _translate("Form", "2单元"))
        self.cmbUnit.setItemText(2, _translate("Form", "3单元"))
        self.cmbUnit.setItemText(3, _translate("Form", "4单元"))
        self.cmbUnit.setItemText(4, _translate("Form", "5单元"))
        self.cmbUnit.setItemText(5, _translate("Form", "6单元"))
        self.label_12.setText(_translate("Form", "常用地址："))
        self.btnNum5.setText(_translate("Form", "5"))
        self.btnNum2.setText(_translate("Form", "2"))
        self.btnNum8.setText(_translate("Form", "8"))
        self.btnNum4.setText(_translate("Form", "4"))
        self.btnNum1.setText(_translate("Form", "1"))
        self.btnNumClear.setText(_translate("Form", "清除"))
        self.btnNumConfirm.setText(_translate("Form", "确认"))
        self.btnNum6.setText(_translate("Form", "6"))
        self.btnNum7.setText(_translate("Form", "7"))
        self.btnNum3.setText(_translate("Form", "3"))
        self.btnNum9.setText(_translate("Form", "9"))
        self.btnNum0.setText(_translate("Form", "0"))
        self.lblKeypadTitle.setText(_translate("Form", "数字键盘"))
        self.btnQuickAddr1.setText(_translate("Form", "1-2-301"))
        self.btnQuickAddr2.setText(_translate("Form", "1-2-301"))
        self.btnQuickAddr3.setText(_translate("Form", "1-2-301"))
        self.btnCreateTaskConfirm.setText(_translate("Form", "确认创建配送任务"))
        self.btnBack.setText(_translate("Form", "<<<返回"))
import ui_pkg.scripts.One_cabin.resources_rc as resources_rc
