# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskSuccessDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(863, 464)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 120, 48, 48))
        self.label.setMinimumSize(QtCore.QSize(48, 48))
        self.label.setMaximumSize(QtCore.QSize(48, 48))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/Finish.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 110, 321, 61))
        self.label_2.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-size: 38px;\n"
"    font-weight: bold;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(300, 160, 261, 61))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgba(37, 37, 37, 120);                  /* 略浅于主文本 */\n"
"    font-size: 20px;\n"
"    font-weight: normal;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(300, 200, 111, 61))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgba(37, 37, 37, 120);\n"
"    font-size: 20px;\n"
"    font-weight: normal;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(400, 200, 211, 61))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: rgb(37, 37, 37);\n"
"    font-size: 22px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 300, 200, 60))
        self.pushButton.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 60))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: #fff;\n"
"    color: #187fe8;\n"
"    border: 2px solid #187fe8;\n"
"    border-radius: 16px;\n"
"    font-size: 24px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 140px;\n"
"    min-height: 54px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 300, 200, 60))
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 60))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 60))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    color: #FFF;\n"
"    border-radius: 16px;\n"
"    font-size: 24px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 140px;\n"
"    min-height: 54px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "投送任务创建成功"))
        self.label_3.setText(_translate("Dialog", "智能物流机器人正在前往配送"))
        self.label_4.setText(_translate("Dialog", "配送地址："))
        self.label_5.setText(_translate("Dialog", "1栋 2单元 301室"))
        self.pushButton.setText(_translate("Dialog", "取消"))
        self.pushButton_2.setText(_translate("Dialog", "确认"))
